apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudvault-agent
  labels:
    app: cloudvault-agent
spec:
  selector:
    matchLabels:
      app: cloudvault-agent
  template:
    metadata:
      labels:
        app: cloudvault-agent
    spec:
      hostPID: true
      hostNetwork: true
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["cloudvault-agent"]
          args:
            - "--interval={{ .Values.agent.interval }}"
            - "--timescale={{ .Values.agent.timescale_conn }}"
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN", "NET_ADMIN"]
          volumeMounts:
            - name: bpf-maps
              mountPath: /sys/fs/bpf
          env:
            - name: TIMESCALE_CONN
              value: {{ .Values.agent.timescale_conn | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      volumes:
        - name: bpf-maps
          hostPath:
            path: /sys/fs/bpf
            type: Directory
