apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudvault-dashboard
  labels:
    app: cloudvault-dashboard
spec:
  replicas: {{ .Values.dashboard.replicaCount }}
  selector:
    matchLabels:
      app: cloudvault-dashboard
  template:
    metadata:
      labels:
        app: cloudvault-dashboard
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: dashboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["cloudvault", "dashboard"]
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.dashboard.resources | nindent 12 }}
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus-server.monitoring.svc.cluster.local:80"
            - name: CLOUDVAULT_ADMIN_USER
              value: "admin"
            - name: CLOUDVAULT_ADMIN_PASSWORD
              value: "cloudvault-secret"
