apiVersion: v1
kind: Service
metadata:
  name: cloudvault-dashboard
  labels:
    app: cloudvault-dashboard
spec:
  type: {{ .Values.dashboard.service.type }}
  ports:
    - port: {{ .Values.dashboard.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: cloudvault-dashboard
